_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  CAFFE_MAXPOOL: True
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  PROPOSAL_GENERATOR:
    HID_CHANNELS: 512
  ANCHOR_GENERATOR:
    SIZES: [[64, 128, 256, 512]]
  ROI_HEADS:
    NUM_CLASSES: 1600
  ROI_BOX_HEAD:
    RES5HALVE: False
    POOLER_TYPE: "ROIPool"
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
